### ISSUE TITLE
Parse's hosted services will be fully retired on January 28, 2017

### ISSUE THREAD

**Issue by dinhhieuac** [bookdash/bookdash-android-app#2]
Hi
https://www.parse.com/

**Comment by spongebobrf** [comment]
Hello,
Yes I have seen this information. Will be migrating to an alternative soon. Might take a bit of time. Thanks for the information.

**Comment by HNeukermans** [comment]
I second that. Nice open source project BTW. Keep up the good work

**Comment by spongebobrf** [comment]
Hi,
I have pushed the app id and client key for the parse instance. You should be able to compile and point to the real server until migration is complete.

**Comment by lgleasain** [comment]
Thinking that Firebase might be a good way to go with this so that we don't need to take on maintaining a web service.

**Comment by spongebobrf** [comment]
The only issue with Firebase is the cost for me $50 a month if 10GB of storage is needed, the books could get quite big so not sure if it would work well. Might be cheaper to get a VM and run the parse server on it?

**Comment by spongebobrf** [comment]
Had a look at Firebase - and have a promo code for 6 months so I think its a good start. I like the offline access - i think it will also solve the other issue that its slow to sync when no internet is present. Will try start importing data into firebase - just to give it a bash.

**Comment by lovebdsobuj** [comment]
@spongebobrf, It's not possible self hosted server plus wordpress json api...?

**Comment by riggaroo** [comment]
Just an update for those interested. We are almost complete with the Firebase migration. The android app on the dev branch is pointing to Firebase. We are in the process of finalizing the backend server and migrating the current books to the new server. Hopefully will release an update soon!

**Comment by riggaroo** [comment]
Hello everyone, an update. 29 days later 😆 
We have rolled out version 2.0.2 to the public, which contains Firebase as a backend instead of Parse. I updated the readme a while ago but it probably needs an update too 😄 

Closing this thread. 🎉
