### ISSUE TITLE
Add instructions on how to upload books to storage

### ISSUE THREAD

**Issue by lidderupk** [bookdash/bookdash-android-app#20]
Hi, 

I was following instructions on how to build the project locally so I hopefully could contribute to this awesome project. I am new to firebase and opensource. Can you provide some instructions on how to upload books to the firebase storage container? Do I need json metadata for each book? Where do I download them from? Thank you.

"You will also then need to place books in the storage container on firebase. You should be able to download some books, upload then and change the URL references to point to your book in your storage container."

**Comment by riggaroo** [comment]
I have added more information to the readme about how to upload and use the books. Let me know if you have any other questions otherwise you can close this.
