### ISSUE TITLE
Make the help tutorial available after first viewing. 

### ISSUE THREAD

**Issue by riggaroo** [bookdash/bookdash-android-app#22]
Make the help tutorial available after first viewing. 
More info: We also wanted to know if it would be possible to make the tutorial screens available after the first time you open the app? Maybe a "Tutorial" option on the menu or added to the "About" section?

**Comment by ugochukwu** [comment]
Do you need some help with implementing that? I'm volunteering :-)

**Comment by riggaroo** [comment]
Hi @ugochukwu 
Sure, this would be great. I think you can add a new settings screen in the navigation drawer with the option to view the help tutorial again. 

Ideally we will add more settings to this screen moving forward in future issues (for example enabling or disabling notifications). So adding a new screen would be a good start. 
If you can fork dev branch and create a pull request that would be awesome!

Thanks.

**Comment by ugochukwu** [comment]
Great, i'll proceed with that. 👍

**Comment by ugochukwu** [comment]
@riggaroo My apologies for the delay in implementing this, I hope you still need it, if so, please have a look at my P.R.
