### ISSUE TITLE
How to import database rules and storage rules into Firebase ?

### ISSUE THREAD

**Issue by JZCheung** [bookdash/bookdash-android-app#26]
Hi, 

Thank you for works. I am pretty new in firebase platform. 

"
The database rules and storage rules can also be imported into Firebase. 
"

I find that the previous rules will be removed when I try to import the database or storage rules. What should I do ?

Can you make a short video guide ? 

Regards,
Js

**Comment by riggaroo** [comment]
Hi there, yes that is correct, the previous rules will be removed when you import new ones.
