### ISSUE TITLE
App crashes after the splash screen on the Nexus 9

### ISSUE THREAD

**Issue by lgleasain** [bookdash/bookdash-android-app#5]
This may also be happening on the Pixel-C,  had a crash after the first run,  but I got it to work after restarting it.

With the Nexus 9 (with all current updates applied),  if you have a fresh install of the application,  you can make it through the intro splash screens,  but then the app exits.  Had a look through the log files and didn't see anything that sticks out during the crash even with a fresh build of the app.

We have tested it on the Nexus 10,  Nexus 7 (2013),  Nexus 7(2012),  and a Sinotec 7inch (wifi only) tablet along with the nexus 4-6p phones with no problem....guessing that it might be due to a native library and the chipset of the 9 but will need to dig.

**Comment by spongebobrf** [comment]
Tried to reproduce on my nexus 9. Doesn't seem to be happening. Will you be able to attach the device logs and I can also take a look?

**Comment by lgleasain** [comment]
A little bit more info that may allow you to reproduce it.  On my Pixel-C it crashes when the tablet is in landscape mode,  but opens up when it is in portrait.  On the Nexus-9 it works in the opposite way where it opens in landscape but not in portrait.    I'll get you some dumps when I'm back at my computer.

**Comment by lgleasain** [comment]
Here are the logs from the released app on a pixel-c

03-02 16:17:43.653 20095-20095/? V/com.parse.ParsePushChannelsController: Tried to subscribe or unsubscribe from a channel, but push is not enabled correctly. Push is not configured for this app because the app manifest is missing required declarations. Please add the following declarations to your app manifest to use GCM for push: make sure that these permissions are declared as children of the root <manifest> element:
03-02 16:17:43.657 20095-20095/? I/GAv4: Google Analytics 8.2.98 is starting up. To enable debug logging on a device run:
                                           adb shell setprop log.tag.GAv4 DEBUG
                                           adb logcat -s GAv4
03-02 16:17:43.667 20095-20128/? V/com.parse.CachedCurrentInstallationController: Successfully deserialized Installation object
03-02 16:17:43.671 20095-20095/? W/GAv4: AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions.
03-02 16:17:43.672 20095-20095/? W/GAv4: CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
03-02 16:17:43.675 20095-20131/? W/GAv4: AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
03-02 16:17:43.776 20095-20132/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
03-02 16:17:43.793 20095-20095/? D/com.parse.push: successfully subscribed to the broadcast channel.
03-02 16:17:43.818 20095-20132/? D/NvOsDebugPrintf: Expected on kernels without fuse support, using silicon
03-02 16:17:43.836 20095-20132/? I/OpenGLRenderer: Initialized EGL, version 1.4
03-02 16:17:44.052 31923-31923/? I/Keyboard.Facilitator: onFinishInput()
03-02 16:17:44.151 20095-20132/? D/libphs: cannot connect to power hinting service: service not available
03-02 16:17:44.166 1125-1167/? I/ActivityManager: Displayed org.bookdash.android/.presentation.splash.SplashActivity: +790ms
03-02 16:17:44.674 1125-18939/? D/DhcpClient: Received packet: e0:f8:47:c8:89:07 OFFER, ip /192.168.10.92, mask /255.255.255.0, DNS servers: /192.168.10.1 /64.134.255.2 /64.134.255.10 , gateways [/192.168.10.1] lease time 3600, domain daskyatlf.atl.wayport.net
03-02 16:17:44.743 1125-1146/? I/ActivityManager: START u0 {cmp=org.bookdash.android/.presentation.listbooks.ListBooksActivity} from uid 10134 on display 0
03-02 16:17:44.776 20095-20095/? I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
03-02 16:17:44.881 1125-18939/? D/DhcpClient: Received packet: 48:74:6e:be:d3:fe ACK: your new IP /192.168.10.184, netmask /255.255.255.0, gateways [/192.168.10.1] DNS servers: /192.168.10.1 /64.134.255.2 /64.134.255.10 , lease time 3600
03-02 16:17:44.952 20095-20095/? E/RecyclerView: No adapter attached; skipping layout
03-02 16:17:44.977 31923-31923/? I/Keyboard.Facilitator: onFinishInput()
03-02 16:17:44.982 20095-20095/? E/RecyclerView: No adapter attached; skipping layout
03-02 16:17:45.054 1125-1167/? I/ActivityManager: Displayed org.bookdash.android/.presentation.listbooks.ListBooksActivity: +307ms
03-02 16:17:45.091 20095-20095/? D/org.bookdash.android.presentation.listbooks.ListBooksActivity: getInvitation:onResult:Status{statusCode=CANCELED, resolution=null}
03-02 16:17:45.422 31923-31923/? I/Keyboard.Facilitator: onFinishInput()
03-02 16:17:45.448 20095-20146/? E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!
03-02 16:17:45.481 1125-1146/? D/GraphicsStats: Buffer count: 8
03-02 16:17:45.483 1125-2601/? I/WindowState: WIN DEATH: Window{a3699ed u0 org.bookdash.android/org.bookdash.android.presentation.listbooks.ListBooksActivity}
03-02 16:17:45.493 992-992/? I/Zygote: Process 20095 exited due to signal (11)
03-02 16:17:45.498 1125-1146/? I/ActivityManager: Process org.bookdash.android (pid 20095) has died
03-02 16:17:45.499 1125-1146/? W/ActivityManager: Force removing ActivityRecord{c76f1ca u0 org.bookdash.android/.presentation.listbooks.ListBooksActivity t469}: app died, no saved state
03-02 16:17:45.577 1125-2133/? W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 20095 uid 10134
03-02 16:17:45.578 31923-31923/? I/Keyboard.Facilitator: onFinishInput()
03-02 16:17:45.667 25812-2120/? W/BaseEntryAdapterFactory: Skipping EntryTreeNode with no group entry and no children

**Comment by lgleasain** [comment]
Looks like the problem is with the BookAdapter.....

This is the last line that is thrown when it crashes.  Will continue to dig.
03-02 16:57:39.868 3299-4913/org.bookdash.android E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!

**Comment by lgleasain** [comment]
This pull request did not work,  but might provide some additional clues.  https://github.com/spongebobrf/BookdashAndroidApp/pull/6

**Comment by spongebobrf** [comment]
Hi Lance, 
Can you try version 1.1.0? I have updated the code around the sizing of the cards and was wondering if it still has an issue for you.

**Comment by spongebobrf** [comment]
@lgleasain  Hi Lance, were you able to reproduce this?
