### ISSUE TITLE
Instead Parse API, Wordpress Json API Possible?

### ISSUE THREAD

**Issue by lovebdsobuj** [bookdash/bookdash-android-app#7]

**Comment by spongebobrf** [comment]
Hi, 
We are migrating to using Firebase so no wordpress API is on the cards.

**Comment by lovebdsobuj** [comment]
Is there any example data like [parse_data_example_json ](https://github.com/bookdash/bookdash-android-app/tree/master/parse_data_example_json) for Firebase. 

And pls, update the `README.md` file about something `Firebase` migration.

**Comment by lgleasain** [comment]
The firebase data structure is a bit different.  You can check out the firebase branch to get an idea of what it will look like along with the https://github.com/bookdash/bookdash-backend-admin-portal project to get an idea of how we are structuring the data.

**Comment by lovebdsobuj** [comment]
Sir, I try https://github.com/bookdash/bookdash-backend-admin-portal but not yet done to serve completely.

Anyway, this **bookdash-android-app** project updated with newly migration with `Firebase`...?
