### ISSUE TITLE
Last releases lack APK file

### ISSUE THREAD

**Issue by IzzySoft** [bookdash/bookdash-android-app#8]
Just asking: Do you no longer publish `releases/` here at GH? The last one listed is 1.0.13 – but the last one on Playstore already 1.0.17?

**Comment by spongebobrf** [comment]
Will upload the next version that gets released. Didn't realise people wanted it there. 😬

**Comment by IzzySoft** [comment]
Great, thanks!

For some background: I love open-source (and use FOSS licenses for all my development). And I don't like being glued into some eco-system plus value privacy quite high (hence I've got no Google-Apps on my Android devices). There are more people thinking like that. Most of them use F-Droid as source for apps. So I have setup a compatible repo to be used with the F-Droid client, for FOSS apps not (yet) available via the official repo. You can [find it here](https://android.izzysoft.de/repo). `.apk` files I pick from Github, and the easiest way to do so is via the `releases/` page. A script regularly checks for updates then, so users of my repo get update notifications and can keep their installations up-to-date directly.

Be welcome to direct your users to my repo as well then if they can't or don't want to use Playstore. There are not only those who don't *want* to use Playstore, but additionally those who *cannot* (due to local restrictions like "the big firewall").

**Comment by spongebobrf** [comment]
Release 1.1.0 is available on the releases page.

**Comment by IzzySoft** [comment]
Thanks a lot, Rebecca! I've just triggered a manual update scan, so 1.1.0 is now also updated in my repo.

**Comment by IzzySoft** [comment]
Umm, on the latest release the APK is missing again. Would you mind attaching it?

**Comment by IzzySoft** [comment]
@riggaroo ^^?

**Comment by riggaroo** [comment]
@HeinrichWesson would you be able to upload the APK to the releases page here on Github?

**Comment by HeinrichWesson** [comment]
@riggaroo it seems I don't have permission to edit releases, only view them. If you can give me access I'm happy to upload the APK, otherwise I've sent you a mail where you can download the APK.

**Comment by riggaroo** [comment]
@HeinrichWesson I've given you access, let me know if it doesn't work. Thanks!

**Comment by HeinrichWesson** [comment]
@riggaroo thanks, that worked. APK uploaded!

**Comment by IzzySoft** [comment]
Thanks a lot, that worked out! Now I'd just wish it came without those trackers, especially as it's an app for children. Do you plan for a "pure FOSS" version? Crashlytics no longer being supported would be a chance in this regard :wink:

**Comment by IzzySoft** [comment]
The last release again lacks its APK – looks like you forgot once more, @HeinrichWesson :wink: And may I ask once more for a build flavor without those proprietary libraries and trackers, for those valuing their privacy? Thanks in advance!

**Comment by IzzySoft** [comment]
PS: as I see you're using storage etc. from Firebase, maybe you'd consider [appwrite](https://github.com/appwrite/appwrite) or [Supabase](https://supabase.com/) as replacements? And some FOSS (and more privacy-friendly) [analytics alternatives](https://gitlab.com/-/snippets/1896503#acceptable-analytics)?

**Comment by IzzySoft** [comment]
Good to read! So I hope you'll get that chance soon. As pointed out, children are especially at risk with those trackers, as they are practically defenseless and usually not even aware of the risks involved.

**Comment by IzzySoft** [comment]
Sad to see you're still stuck with this:

```gradle
    // Import the Firebase Bill of Materials (BoM)
    implementation platform('com.google.firebase:firebase-bom:33.1.2')

    // Firebase Dependencies
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-config'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-perf'
    implementation 'com.google.firebase:firebase-storage'
```

Would love to add your app back to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) – but as long as those are present, we can't, as that violates our inclusion policy 😢 Children must not be tracked, they need special protection there…
